### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bonyhardian** [imran0101/Fliptext#1]
Hi bro,

Can I use your code with Public Domain License or MIT License?

Thanks

**Comment by bonyhardian** [comment]
Hi bro,

Can I use your code for my project?
https://choosealicense.com/

Thanks

**Comment by imran0101** [comment]
@bonyhardian 

https://github.com/imran0101/Fliptext/blob/master/LICENSE
Free to use. Thanks.

**Comment by bonyhardian** [comment]
Hi bro,

Thank you for your permission.

Cheers
